Removed findBugsEclipsePlugin/META-INF/p2.inf.
Removed p2.inf because it generated the following exception during the installation of Keshmesh:

No action found for: org.eclipse.equinox.p2.touchpoint.eclipse.addJVMArg.

java.lang.IllegalArgumentException: No action found for: org.eclipse.equinox.p2.touchpoint.eclipse.addJVMArg.
at org.eclipse.equinox.internal.p2.engine.MissingAction.execute(MissingAction.java:42)
at org.eclipse.equinox.internal.p2.engine.Phase.mainPerform(Phase.java:149)
at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:78)
at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:44)
at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:73)
at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:44)
at org.eclipse.equinox.p2.operations.ProvisioningSession.performProvisioningPlan(ProvisioningSession.java:174)
at org.eclipse.equinox.p2.operations.ProfileModificationJob.runModal(ProfileModificationJob.java:79)
at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:177)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

This commit belongs to issue #38.